### ISSUE TITLE
Broken URLs

### ISSUE THREAD

**Issue by Haroon96** [yifan0sun/DynamicWord2Vec#2]
The links to the data files in the README appear to be broken. Can you please update those?

**Comment by Haroon96** [comment]
Similar to #1 
Broken links

- https://www.dropbox.com/s/nifi5nj1oj0fu2i/data.zip?dl=0
- https://www.dropbox.com/s/tzkaoagzxuxtwqs/data.zip?dl=0
- https://www.dropbox.com/s/6q5jhhmxdmc8n1e/data.zip?dl=0

**Comment by yifan0sun** [comment]
Ok, I think I fixed it. Can you try again and report what you see?

**Comment by Haroon96** [comment]
Yes, fixed. Thank you!
