### ISSUE TITLE
Code error while running your code to train the model.

### ISSUE THREAD

**Issue by Soothysay** [yifan0sun/DynamicWord2Vec#7]
Hi,
I am trying to get dynamic embeddings for my dataset. I have the data file in the format word,context,ppmi. But while running the main train script, I get the following error:
```
Traceback (most recent call last):
  File "train_time_CD_smallnyt.py", line 115, in <module>
    pmi_seg = pmi[:,ind].todense()
AttributeError: 'matrix' object has no attribute 'todense'
```
Can you help me understand why this is happening?

**Comment by yifan0sun** [comment]
Can you print out what "type(pmi)" returns? todense only works if the object is a sparse matrix; if it was casted as a dense matrix or ndarray at any point then this command would fail. (So, the solution is to just wrap around it: if type(pmi) != scipy.sparse.coo_matrix, pmi_seg = pmi[:,ind] or something like that.)

**Comment by Soothysay** [comment]
Yes, you already pass the pmi matrix as a dense matrix in util_timeCD.getmat. Thanks for the help!
